export const GET_USER_MESSAGE = 'GET_USER_MESSAGE';
export const GET_BUNDLES = 'GET_BUNDLES';
export const GET_LATEST_OPEN = 'GET_LATEST_OPEN';
export const GET_CURRENT = 'GET_CURRENT';
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
export const SELECT_PROJECT_NEW = 'SELECT_PROJECT_NEW';
export const SELECT_PROJECT_FIRST = 'SELECT_PROJECT_FIRST';
export const SELECT_PROJECT_REST = 'SELECT_PROJECT_REST';
export const CHANGE_ORG_SHOW = 'CHANGE_ORG_SHOW';
export const SELECT_ORGANIZATION = 'SELECT_ORGANIZATION';
export const SELECT_LIST_DOWNLOADING = 'SELECT_LIST_DOWNLOADING';
export const REMOVE_LIST_DOWNLOADING = 'REMOVE_LIST_DOWNLOADING';

export const GET_PROJECTS_ING = 'GET_PROJECTS_ING';
export const GET_PROJECTS_Success = 'GET_PROJECTS_Success';